# .github/workflows/deploy.yml
# This workflow builds and deploys the application to Google Cloud Run

name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  BUCKET_NAME: "fashion-recommender-models" # IMPORTANT: Change to your bucket name
  REGION: "asia-south2"
  SERVICE_NAME: "trendblend-service"

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth # Give this step an ID
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # --- NEW DEBUGGING STEP ---
      # This step will run right after authentication to verify which account is active.
      - name: 'Debug: Display Authenticated User and Project'
        run: |-
          echo "-----------------------------------------------------"
          echo "DEBUGGING AUTHENTICATION"
          echo "-----------------------------------------------------"
          echo "Step name: Authenticate to Google Cloud"
          echo "Step output (credentials_file_path): ${{ steps.auth.outputs.credentials_file_path }}"
          echo ""
          echo "Running 'gcloud auth list' to see the active account:"
          gcloud auth list
          echo ""
          echo "Running 'gcloud config list' to see the configured project:"
          gcloud config list --format="value(core.project)"
          echo "-----------------------------------------------------"
      # --- END OF DEBUGGING STEP ---

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Build and Push Docker Image
        run: |-
          gcloud builds submit --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME"

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy $SERVICE_NAME \
            --image="gcr.io/$PROJECT_ID/$SERVICE_NAME" \
            --platform="managed" \
            --region="$REGION" \
            --min-instances=1 \
            --memory=2Gi \
            --cpu=2 \
            --allow-unauthenticated \
            --set-env-vars="BUCKET_NAME=$BUCKET_NAME"
